/* Generated by Yosys 0.29 (git sha1 9c5a60eb201, clang 14.0.3 -fPIC -Os) */
/* verilator lint_off DECLFILENAME */
(* hdlname = "\\PmodJSTK" *)
(* top =  1  *)
(* src = "PmodJSTK.sv:1.1-72.10" *)
module PmodJSTK(clk_12mhz_i, reset_i, data_i, spi_sd_i, spi_cs_o, spi_sck_o, spi_sd_o, data_o);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  (* src = "PmodJSTK.sv:57.4-61.7|ClkDiv_66_67kHz.sv:23.22-23.28" *)
  wire _115_;
  (* src = "PmodJSTK.sv:66.4-70.7|ClkDiv_20Hz.sv:22.15-22.21" *)
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  (* force_downto = 32'd1 *)
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:186.18-186.34|/opt/homebrew/bin/../share/yosys/techmap.v:279.21-279.23" *)
  (* unused_bits = "1 2 3 4" *)
  wire [4:0] _226_;
  (* force_downto = 32'd1 *)
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:183.27-183.42|/opt/homebrew/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [4:0] _227_;
  (* force_downto = 32'd1 *)
  (* src = "PmodJSTK.sv:57.4-61.7|ClkDiv_66_67kHz.sv:27.24-27.38|/opt/homebrew/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [6:0] _228_;
  (* force_downto = 32'd1 *)
  (* src = "PmodJSTK.sv:57.4-61.7|ClkDiv_66_67kHz.sv:27.24-27.38|/opt/homebrew/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [6:0] _229_;
  (* force_downto = 32'd1 *)
  (* src = "PmodJSTK.sv:66.4-70.7|ClkDiv_20Hz.sv:26.17-26.31|/opt/homebrew/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [18:0] _230_;
  (* force_downto = 32'd1 *)
  (* src = "PmodJSTK.sv:66.4-70.7|ClkDiv_20Hz.sv:26.17-26.31|/opt/homebrew/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [18:0] _231_;
  (* force_downto = 32'd1 *)
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:74.10-181.17|spiCtrl.v:0.0-0.0|/opt/homebrew/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire [2:0] _232_;
  (* force_downto = 32'd1 *)
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:148.10-219.17|spiMode0.sv:0.0-0.0|/opt/homebrew/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire [1:0] _233_;
  (* hdlname = "SPI_Ctrl BUSY" *)
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:21.10-21.14" *)
  wire \SPI_Ctrl.BUSY ;
  (* hdlname = "SPI_Ctrl DIN" *)
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:22.17-22.20" *)
  wire [39:0] \SPI_Ctrl.DIN ;
  (* hdlname = "SPI_Ctrl DOUT" *)
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:27.18-27.22" *)
  reg [39:0] \SPI_Ctrl.DOUT  = 40'h0000000000;
  (* hdlname = "SPI_Ctrl RxData" *)
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:23.17-23.23" *)
  wire [7:0] \SPI_Ctrl.RxData ;
  (* hdlname = "SPI_Ctrl SS" *)
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:24.17-24.19" *)
  reg \SPI_Ctrl.SS  = 1'h1;
  (* hdlname = "SPI_Ctrl byteCnt" *)
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:49.20-49.27" *)
  reg [2:0] \SPI_Ctrl.byteCnt  = 3'h0;
  (* hdlname = "SPI_Ctrl clk_i" *)
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:18.10-18.15" *)
  wire \SPI_Ctrl.clk_i ;
  (* hdlname = "SPI_Ctrl getByte" *)
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:25.17-25.24" *)
  reg \SPI_Ctrl.getByte  = 1'h0;
  (* hdlname = "SPI_Ctrl pState" *)
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:47.20-47.26" *)
  reg [2:0] \SPI_Ctrl.pState  = 3'h0;
  (* hdlname = "SPI_Ctrl reset_i" *)
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:19.10-19.17" *)
  wire \SPI_Ctrl.reset_i ;
  (* hdlname = "SPI_Ctrl sndData" *)
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:26.17-26.24" *)
  reg [7:0] \SPI_Ctrl.sndData  = 8'h00;
  (* hdlname = "SPI_Ctrl sndRec" *)
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:20.10-20.16" *)
  wire \SPI_Ctrl.sndRec ;
  (* hdlname = "SPI_Ctrl tmpSR" *)
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:51.20-51.25" *)
  reg [39:0] \SPI_Ctrl.tmpSR  = 40'h0000000000;
  (* hdlname = "SPI_Ctrl tmpSRsend" *)
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:53.20-53.29" *)
  reg [39:0] \SPI_Ctrl.tmpSRsend  = 40'h0000000000;
  (* hdlname = "SPI_Int BUSY" *)
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:25.16-25.20" *)
  reg \SPI_Int.BUSY ;
  (* hdlname = "SPI_Int CE" *)
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:47.20-47.22" *)
  reg \SPI_Int.CE  = 1'h0;
  (* hdlname = "SPI_Int CLK" *)
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:18.10-18.13" *)
  wire \SPI_Int.CLK ;
  (* hdlname = "SPI_Int DIN" *)
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:21.16-21.19" *)
  wire [7:0] \SPI_Int.DIN ;
  (* hdlname = "SPI_Int DOUT" *)
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:26.17-26.21" *)
  wire [7:0] \SPI_Int.DOUT ;
  (* hdlname = "SPI_Int MISO" *)
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:22.16-22.20" *)
  wire \SPI_Int.MISO ;
  (* hdlname = "SPI_Int MOSI" *)
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:23.16-23.20" *)
  wire \SPI_Int.MOSI ;
  (* hdlname = "SPI_Int RST" *)
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:19.10-19.13" *)
  wire \SPI_Int.RST ;
  (* hdlname = "SPI_Int SCLK" *)
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:24.16-24.20" *)
  wire \SPI_Int.SCLK ;
  (* hdlname = "SPI_Int bitCount" *)
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:42.20-42.28" *)
  reg [4:0] \SPI_Int.bitCount ;
  (* hdlname = "SPI_Int pState" *)
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:45.20-45.26" *)
  reg [1:0] \SPI_Int.pState  = 2'h0;
  (* hdlname = "SPI_Int rSR" *)
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:43.20-43.23" *)
  reg [7:0] \SPI_Int.rSR  = 8'h00;
  (* hdlname = "SPI_Int sndRec" *)
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:20.10-20.16" *)
  wire \SPI_Int.sndRec ;
  (* hdlname = "SPI_Int wSR" *)
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:44.20-44.23" *)
  reg [7:0] \SPI_Int.wSR  = 8'h00;
  (* hdlname = "SerialClock clk_i" *)
  (* src = "PmodJSTK.sv:57.4-61.7|ClkDiv_66_67kHz.sv:2.16-2.21" *)
  wire \SerialClock.clk_i ;
  (* hdlname = "SerialClock clk_o" *)
  (* src = "PmodJSTK.sv:57.4-61.7|ClkDiv_66_67kHz.sv:4.17-4.22" *)
  wire \SerialClock.clk_o ;
  (* hdlname = "SerialClock clk_r" *)
  (* src = "PmodJSTK.sv:57.4-61.7|ClkDiv_66_67kHz.sv:10.11-10.16" *)
  reg \SerialClock.clk_r  = 1'h1;
  (* hdlname = "SerialClock count_r" *)
  (* src = "PmodJSTK.sv:57.4-61.7|ClkDiv_66_67kHz.sv:15.16-15.23" *)
  reg [6:0] \SerialClock.count_r  = 7'h00;
  (* hdlname = "SerialClock reset_i" *)
  (* src = "PmodJSTK.sv:57.4-61.7|ClkDiv_66_67kHz.sv:3.16-3.23" *)
  wire \SerialClock.reset_i ;
  (* src = "PmodJSTK.sv:14.18-14.24" *)
  wire busy_o;
  (* src = "PmodJSTK.sv:2.19-2.30" *)
  input clk_12mhz_i;
  wire clk_12mhz_i;
  (* src = "PmodJSTK.sv:17.18-17.28" *)
  wire clk_20hz_o;
  (* src = "PmodJSTK.sv:21.18-21.32" *)
  wire clk_66_67khz_o;
  (* src = "PmodJSTK.sv:4.19-4.25" *)
  input [39:0] data_i;
  wire [39:0] data_i;
  (* src = "PmodJSTK.sv:9.19-9.25" *)
  output [39:0] data_o;
  wire [39:0] data_o;
  (* hdlname = "genSndRec clk_i" *)
  (* src = "PmodJSTK.sv:66.4-70.7|ClkDiv_20Hz.sv:2.16-2.21" *)
  wire \genSndRec.clk_i ;
  (* hdlname = "genSndRec clk_o" *)
  (* src = "PmodJSTK.sv:66.4-70.7|ClkDiv_20Hz.sv:4.17-4.22" *)
  wire \genSndRec.clk_o ;
  (* hdlname = "genSndRec clk_r" *)
  (* src = "PmodJSTK.sv:66.4-70.7|ClkDiv_20Hz.sv:7.19-7.24" *)
  reg \genSndRec.clk_r  = 1'h1;
  (* hdlname = "genSndRec count_r" *)
  (* src = "PmodJSTK.sv:66.4-70.7|ClkDiv_20Hz.sv:10.17-10.24" *)
  reg [18:0] \genSndRec.count_r  = 19'h00000;
  (* hdlname = "genSndRec reset_i" *)
  (* src = "PmodJSTK.sv:66.4-70.7|ClkDiv_20Hz.sv:3.16-3.23" *)
  wire \genSndRec.reset_i ;
  (* src = "PmodJSTK.sv:3.19-3.26" *)
  input reset_i;
  wire reset_i;
  (* src = "PmodJSTK.sv:13.18-13.27" *)
  wire [7:0] rx_data_i;
  (* src = "PmodJSTK.sv:6.19-6.27" *)
  output spi_cs_o;
  wire spi_cs_o;
  (* src = "PmodJSTK.sv:7.19-7.28" *)
  output spi_sck_o;
  wire spi_sck_o;
  (* src = "PmodJSTK.sv:5.19-5.27" *)
  input spi_sd_i;
  wire spi_sd_i;
  (* src = "PmodJSTK.sv:8.19-8.27" *)
  output spi_sd_o;
  wire spi_sd_o;
  (* src = "PmodJSTK.sv:12.18-12.27" *)
  wire [7:0] tx_data_o;
  (* src = "PmodJSTK.sv:18.18-18.27" *)
  wire tx_not_rx;
  assign _226_[0] = ~\SPI_Int.bitCount [0];
  assign _228_[0] = ~\SerialClock.count_r [0];
  assign _230_[0] = ~\genSndRec.count_r [0];
  assign _117_ = \SerialClock.count_r [1] & ~(\SerialClock.count_r [0]);
  assign _118_ = \SerialClock.count_r [2] | ~(\SerialClock.count_r [3]);
  assign _119_ = _117_ & ~(_118_);
  assign _120_ = \SerialClock.count_r [4] & ~(\SerialClock.count_r [5]);
  assign _121_ = ~(_120_ & \SerialClock.count_r [6]);
  assign _012_ = _121_ | ~(_119_);
  assign _008_ = reset_i | ~(_012_);
  assign _122_ = \SPI_Int.pState [1] & ~(\SPI_Int.pState [0]);
  assign _123_ = ~(\SPI_Int.pState [1] | \SPI_Int.pState [0]);
  assign _004_ = _122_ ? \SPI_Int.CE  : _123_;
  assign _124_ = ~(\genSndRec.count_r [1] | \genSndRec.count_r [0]);
  assign _125_ = \genSndRec.count_r [3] | \genSndRec.count_r [2];
  assign _126_ = _124_ & ~(_125_);
  assign _127_ = \genSndRec.count_r [4] | ~(\genSndRec.count_r [5]);
  assign _128_ = ~(\genSndRec.count_r [6] & \genSndRec.count_r [7]);
  assign _129_ = _128_ | _127_;
  assign _130_ = _126_ & ~(_129_);
  assign _131_ = ~(\genSndRec.count_r [9] & \genSndRec.count_r [8]);
  assign _132_ = \genSndRec.count_r [11] | \genSndRec.count_r [10];
  assign _133_ = _132_ | _131_;
  assign _134_ = \genSndRec.count_r [13] | ~(\genSndRec.count_r [12]);
  assign _135_ = \genSndRec.count_r [14] | ~(\genSndRec.count_r [15]);
  assign _136_ = _135_ | _134_;
  assign _137_ = _136_ | _133_;
  assign _138_ = _130_ & ~(_137_);
  assign _139_ = ~(\genSndRec.count_r [17] | \genSndRec.count_r [16]);
  assign _140_ = ~(_139_ & \genSndRec.count_r [18]);
  assign _013_ = _140_ | ~(_138_);
  assign _007_ = reset_i | ~(_013_);
  assign _141_ = ~\SPI_Ctrl.pState [2];
  assign _142_ = ~(\SPI_Ctrl.pState [0] & \SPI_Ctrl.pState [1]);
  assign _143_ = _141_ & ~(_142_);
  assign _144_ = \SPI_Ctrl.pState [0] | \SPI_Ctrl.pState [1];
  assign _145_ = _141_ & ~(_144_);
  assign _000_ = _145_ | _143_;
  assign _005_ = _122_ & \SPI_Int.CE ;
  assign _146_ = \SPI_Ctrl.pState [2] & ~(_144_);
  assign _010_ = _146_ | _145_;
  assign _147_ = \SPI_Ctrl.pState [1] & ~(\SPI_Ctrl.pState [2]);
  assign _148_ = \SPI_Ctrl.pState [1] | ~(\SPI_Ctrl.pState [0]);
  assign _149_ = _141_ & ~(_148_);
  assign _150_ = _149_ | _147_;
  assign _003_ = _150_ | _010_;
  assign _022_ = \SPI_Ctrl.pState [1] ? \SPI_Ctrl.pState [2] : \SPI_Ctrl.pState [0];
  assign _002_ = _149_ | ~(_022_);
  assign _001_ = _149_ | _010_;
  assign _006_ = _149_ ? \SPI_Int.BUSY  : _145_;
  assign _011_ = \SPI_Int.pState [1] | \SPI_Int.pState [0];
  assign _151_ = _123_ | reset_i;
  assign _152_ = \SPI_Int.pState [0] & ~(\SPI_Int.pState [1]);
  assign _153_ = \SPI_Int.pState [1] & \SPI_Int.pState [0];
  assign _154_ = _153_ | _152_;
  assign _009_ = _154_ | _151_;
  assign _155_ = _142_ | \SPI_Ctrl.pState [2];
  assign _156_ = ~\SPI_Ctrl.byteCnt [2];
  assign _157_ = \SPI_Ctrl.byteCnt [1] | ~(\SPI_Ctrl.byteCnt [0]);
  assign _158_ = _157_ | _156_;
  assign _159_ = _158_ & ~(_155_);
  assign _160_ = _149_ & ~(\SPI_Int.BUSY );
  assign _161_ = ~\SPI_Int.BUSY ;
  assign _162_ = \SPI_Ctrl.pState [0] | ~(\SPI_Ctrl.pState [1]);
  assign _163_ = _162_ | \SPI_Ctrl.pState [2];
  assign _164_ = _161_ & ~(_163_);
  assign _165_ = _164_ | _160_;
  assign _166_ = _165_ | _159_;
  assign _116_ = ~\genSndRec.clk_r ;
  assign _167_ = _145_ & ~(_116_);
  assign _168_ = _167_ | _166_;
  assign _169_ = _146_ | _143_;
  assign _170_ = _149_ | ~(_163_);
  assign _171_ = _170_ | _169_;
  assign _172_ = _171_ | _145_;
  assign _232_[0] = _172_ & _168_;
  assign _173_ = _149_ & ~(_161_);
  assign _174_ = _163_ & ~(_173_);
  assign _232_[1] = _172_ & ~(_174_);
  assign _175_ = ~(_146_ & \genSndRec.clk_r );
  assign _176_ = _143_ & ~(_158_);
  assign _177_ = _175_ & ~(_176_);
  assign _232_[2] = _172_ & ~(_177_);
  assign _178_ = \SPI_Int.bitCount [3] & ~(\SPI_Int.bitCount [2]);
  assign _179_ = \SPI_Int.bitCount [1] | \SPI_Int.bitCount [0];
  assign _180_ = _178_ & ~(_179_);
  assign _181_ = \SPI_Int.bitCount [4] | ~(_180_);
  assign _182_ = _122_ & ~(_181_);
  assign _233_[0] = _123_ ? \SPI_Ctrl.getByte  : _182_;
  assign _233_[1] = _152_ | _122_;
  assign _014_ = \SPI_Ctrl.tmpSRsend [32] & ~(_010_);
  assign _015_ = \SPI_Ctrl.tmpSRsend [33] & ~(_010_);
  assign _016_ = \SPI_Ctrl.tmpSRsend [34] & ~(_010_);
  assign _017_ = \SPI_Ctrl.tmpSRsend [35] & ~(_010_);
  assign _018_ = \SPI_Ctrl.tmpSRsend [36] & ~(_010_);
  assign _019_ = \SPI_Ctrl.tmpSRsend [37] & ~(_010_);
  assign _020_ = \SPI_Ctrl.tmpSRsend [38] & ~(_010_);
  assign _021_ = \SPI_Ctrl.tmpSRsend [39] & ~(_010_);
  assign _103_ = _149_ & ~(\SPI_Ctrl.byteCnt [0]);
  assign _183_ = ~(\SPI_Ctrl.byteCnt [1] ^ \SPI_Ctrl.byteCnt [0]);
  assign _104_ = _149_ & ~(_183_);
  assign _184_ = \SPI_Ctrl.byteCnt [1] & \SPI_Ctrl.byteCnt [0];
  assign _185_ = _184_ ^ _156_;
  assign _105_ = _149_ & ~(_185_);
  assign _063_ = \SPI_Int.rSR [0] & ~(_155_);
  assign _074_ = \SPI_Int.rSR [1] & ~(_155_);
  assign _085_ = \SPI_Int.rSR [2] & ~(_155_);
  assign _096_ = \SPI_Int.rSR [3] & ~(_155_);
  assign _097_ = \SPI_Int.rSR [4] & ~(_155_);
  assign _098_ = \SPI_Int.rSR [5] & ~(_155_);
  assign _099_ = \SPI_Int.rSR [6] & ~(_155_);
  assign _100_ = \SPI_Int.rSR [7] & ~(_155_);
  assign _101_ = \SPI_Ctrl.tmpSR [0] & ~(_155_);
  assign _102_ = \SPI_Ctrl.tmpSR [1] & ~(_155_);
  assign _064_ = \SPI_Ctrl.tmpSR [2] & ~(_155_);
  assign _065_ = \SPI_Ctrl.tmpSR [3] & ~(_155_);
  assign _066_ = \SPI_Ctrl.tmpSR [4] & ~(_155_);
  assign _067_ = \SPI_Ctrl.tmpSR [5] & ~(_155_);
  assign _068_ = \SPI_Ctrl.tmpSR [6] & ~(_155_);
  assign _069_ = \SPI_Ctrl.tmpSR [7] & ~(_155_);
  assign _070_ = \SPI_Ctrl.tmpSR [8] & ~(_155_);
  assign _071_ = \SPI_Ctrl.tmpSR [9] & ~(_155_);
  assign _072_ = \SPI_Ctrl.tmpSR [10] & ~(_155_);
  assign _073_ = \SPI_Ctrl.tmpSR [11] & ~(_155_);
  assign _075_ = \SPI_Ctrl.tmpSR [12] & ~(_155_);
  assign _076_ = \SPI_Ctrl.tmpSR [13] & ~(_155_);
  assign _077_ = \SPI_Ctrl.tmpSR [14] & ~(_155_);
  assign _078_ = \SPI_Ctrl.tmpSR [15] & ~(_155_);
  assign _079_ = \SPI_Ctrl.tmpSR [16] & ~(_155_);
  assign _080_ = \SPI_Ctrl.tmpSR [17] & ~(_155_);
  assign _081_ = \SPI_Ctrl.tmpSR [18] & ~(_155_);
  assign _082_ = \SPI_Ctrl.tmpSR [19] & ~(_155_);
  assign _083_ = \SPI_Ctrl.tmpSR [20] & ~(_155_);
  assign _084_ = \SPI_Ctrl.tmpSR [21] & ~(_155_);
  assign _086_ = \SPI_Ctrl.tmpSR [22] & ~(_155_);
  assign _087_ = \SPI_Ctrl.tmpSR [23] & ~(_155_);
  assign _088_ = \SPI_Ctrl.tmpSR [24] & ~(_155_);
  assign _089_ = \SPI_Ctrl.tmpSR [25] & ~(_155_);
  assign _090_ = \SPI_Ctrl.tmpSR [26] & ~(_155_);
  assign _091_ = \SPI_Ctrl.tmpSR [27] & ~(_155_);
  assign _092_ = \SPI_Ctrl.tmpSR [28] & ~(_155_);
  assign _093_ = \SPI_Ctrl.tmpSR [29] & ~(_155_);
  assign _094_ = \SPI_Ctrl.tmpSR [30] & ~(_155_);
  assign _095_ = \SPI_Ctrl.tmpSR [31] & ~(_155_);
  assign _023_ = data_i[0] & ~(_143_);
  assign _034_ = data_i[1] & ~(_143_);
  assign _045_ = data_i[2] & ~(_143_);
  assign _056_ = data_i[3] & ~(_143_);
  assign _057_ = data_i[4] & ~(_143_);
  assign _058_ = data_i[5] & ~(_143_);
  assign _059_ = data_i[6] & ~(_143_);
  assign _060_ = data_i[7] & ~(_143_);
  assign _061_ = _143_ ? \SPI_Ctrl.tmpSRsend [0] : data_i[8];
  assign _062_ = _143_ ? \SPI_Ctrl.tmpSRsend [1] : data_i[9];
  assign _024_ = _143_ ? \SPI_Ctrl.tmpSRsend [2] : data_i[10];
  assign _025_ = _143_ ? \SPI_Ctrl.tmpSRsend [3] : data_i[11];
  assign _026_ = _143_ ? \SPI_Ctrl.tmpSRsend [4] : data_i[12];
  assign _027_ = _143_ ? \SPI_Ctrl.tmpSRsend [5] : data_i[13];
  assign _028_ = _143_ ? \SPI_Ctrl.tmpSRsend [6] : data_i[14];
  assign _029_ = _143_ ? \SPI_Ctrl.tmpSRsend [7] : data_i[15];
  assign _030_ = _143_ ? \SPI_Ctrl.tmpSRsend [8] : data_i[16];
  assign _031_ = _143_ ? \SPI_Ctrl.tmpSRsend [9] : data_i[17];
  assign _032_ = _143_ ? \SPI_Ctrl.tmpSRsend [10] : data_i[18];
  assign _033_ = _143_ ? \SPI_Ctrl.tmpSRsend [11] : data_i[19];
  assign _035_ = _143_ ? \SPI_Ctrl.tmpSRsend [12] : data_i[20];
  assign _036_ = _143_ ? \SPI_Ctrl.tmpSRsend [13] : data_i[21];
  assign _037_ = _143_ ? \SPI_Ctrl.tmpSRsend [14] : data_i[22];
  assign _038_ = _143_ ? \SPI_Ctrl.tmpSRsend [15] : data_i[23];
  assign _039_ = _143_ ? \SPI_Ctrl.tmpSRsend [16] : data_i[24];
  assign _040_ = _143_ ? \SPI_Ctrl.tmpSRsend [17] : data_i[25];
  assign _041_ = _143_ ? \SPI_Ctrl.tmpSRsend [18] : data_i[26];
  assign _042_ = _143_ ? \SPI_Ctrl.tmpSRsend [19] : data_i[27];
  assign _043_ = _143_ ? \SPI_Ctrl.tmpSRsend [20] : data_i[28];
  assign _044_ = _143_ ? \SPI_Ctrl.tmpSRsend [21] : data_i[29];
  assign _046_ = _143_ ? \SPI_Ctrl.tmpSRsend [22] : data_i[30];
  assign _047_ = _143_ ? \SPI_Ctrl.tmpSRsend [23] : data_i[31];
  assign _048_ = _143_ ? \SPI_Ctrl.tmpSRsend [24] : data_i[32];
  assign _049_ = _143_ ? \SPI_Ctrl.tmpSRsend [25] : data_i[33];
  assign _050_ = _143_ ? \SPI_Ctrl.tmpSRsend [26] : data_i[34];
  assign _051_ = _143_ ? \SPI_Ctrl.tmpSRsend [27] : data_i[35];
  assign _052_ = _143_ ? \SPI_Ctrl.tmpSRsend [28] : data_i[36];
  assign _053_ = _143_ ? \SPI_Ctrl.tmpSRsend [29] : data_i[37];
  assign _054_ = _143_ ? \SPI_Ctrl.tmpSRsend [30] : data_i[38];
  assign _055_ = _143_ ? \SPI_Ctrl.tmpSRsend [31] : data_i[39];
  assign _107_ = \SPI_Ctrl.sndData [0] & ~(_122_);
  assign _108_ = _122_ ? \SPI_Int.wSR [0] : \SPI_Ctrl.sndData [1];
  assign _109_ = _122_ ? \SPI_Int.wSR [1] : \SPI_Ctrl.sndData [2];
  assign _110_ = _122_ ? \SPI_Int.wSR [2] : \SPI_Ctrl.sndData [3];
  assign _111_ = _122_ ? \SPI_Int.wSR [3] : \SPI_Ctrl.sndData [4];
  assign _112_ = _122_ ? \SPI_Int.wSR [4] : \SPI_Ctrl.sndData [5];
  assign _113_ = _122_ ? \SPI_Int.wSR [5] : \SPI_Ctrl.sndData [6];
  assign _114_ = _122_ ? \SPI_Int.wSR [6] : \SPI_Ctrl.sndData [7];
  assign _186_ = \SPI_Int.bitCount [3] & ~(_180_);
  assign _187_ = _186_ | \SPI_Int.bitCount [4];
  assign _106_ = _181_ & ~(_187_);
  assign _115_ = ~\SerialClock.clk_r ;
  assign _227_[1] = \SPI_Int.bitCount [1] ^ \SPI_Int.bitCount [0];
  assign _188_ = \SPI_Int.bitCount [1] & \SPI_Int.bitCount [0];
  assign _227_[2] = _188_ ^ \SPI_Int.bitCount [2];
  assign _189_ = _188_ & \SPI_Int.bitCount [2];
  assign _227_[3] = _189_ ^ \SPI_Int.bitCount [3];
  assign _190_ = ~(\SPI_Int.bitCount [3] & \SPI_Int.bitCount [2]);
  assign _191_ = _188_ & ~(_190_);
  assign _227_[4] = _191_ ^ \SPI_Int.bitCount [4];
  assign _229_[1] = \SerialClock.count_r [1] ^ \SerialClock.count_r [0];
  assign _192_ = \SerialClock.count_r [1] & \SerialClock.count_r [0];
  assign _229_[2] = _192_ ^ \SerialClock.count_r [2];
  assign _193_ = _192_ & \SerialClock.count_r [2];
  assign _229_[3] = _193_ ^ \SerialClock.count_r [3];
  assign _194_ = ~(\SerialClock.count_r [3] & \SerialClock.count_r [2]);
  assign _195_ = _192_ & ~(_194_);
  assign _229_[4] = _195_ ^ \SerialClock.count_r [4];
  assign _196_ = _195_ & \SerialClock.count_r [4];
  assign _229_[5] = _196_ ^ \SerialClock.count_r [5];
  assign _197_ = ~(\SerialClock.count_r [4] & \SerialClock.count_r [5]);
  assign _198_ = _195_ & ~(_197_);
  assign _229_[6] = _198_ ^ \SerialClock.count_r [6];
  assign _231_[1] = \genSndRec.count_r [1] ^ \genSndRec.count_r [0];
  assign _199_ = ~(\genSndRec.count_r [1] & \genSndRec.count_r [0]);
  assign _231_[2] = ~(_199_ ^ \genSndRec.count_r [2]);
  assign _200_ = \genSndRec.count_r [2] & ~(_199_);
  assign _231_[3] = _200_ ^ \genSndRec.count_r [3];
  assign _201_ = ~(\genSndRec.count_r [3] & \genSndRec.count_r [2]);
  assign _202_ = _201_ | _199_;
  assign _231_[4] = ~(_202_ ^ \genSndRec.count_r [4]);
  assign _203_ = \genSndRec.count_r [4] & ~(_202_);
  assign _231_[5] = _203_ ^ \genSndRec.count_r [5];
  assign _204_ = ~(\genSndRec.count_r [4] & \genSndRec.count_r [5]);
  assign _205_ = _204_ | _202_;
  assign _231_[6] = ~(_205_ ^ \genSndRec.count_r [6]);
  assign _206_ = \genSndRec.count_r [6] & ~(_205_);
  assign _231_[7] = _206_ ^ \genSndRec.count_r [7];
  assign _207_ = _204_ | _128_;
  assign _208_ = _207_ | _202_;
  assign _231_[8] = ~(_208_ ^ \genSndRec.count_r [8]);
  assign _209_ = \genSndRec.count_r [8] & ~(_208_);
  assign _231_[9] = _209_ ^ \genSndRec.count_r [9];
  assign _210_ = _208_ | _131_;
  assign _231_[10] = ~(_210_ ^ \genSndRec.count_r [10]);
  assign _211_ = \genSndRec.count_r [10] & ~(_210_);
  assign _231_[11] = _211_ ^ \genSndRec.count_r [11];
  assign _212_ = ~(\genSndRec.count_r [11] & \genSndRec.count_r [10]);
  assign _213_ = _212_ | _131_;
  assign _214_ = _213_ | _208_;
  assign _231_[12] = ~(_214_ ^ \genSndRec.count_r [12]);
  assign _215_ = \genSndRec.count_r [12] & ~(_214_);
  assign _231_[13] = _215_ ^ \genSndRec.count_r [13];
  assign _216_ = ~(\genSndRec.count_r [13] & \genSndRec.count_r [12]);
  assign _217_ = _216_ | _214_;
  assign _231_[14] = ~(_217_ ^ \genSndRec.count_r [14]);
  assign _218_ = \genSndRec.count_r [14] & ~(_217_);
  assign _231_[15] = _218_ ^ \genSndRec.count_r [15];
  assign _219_ = ~(\genSndRec.count_r [14] & \genSndRec.count_r [15]);
  assign _220_ = _219_ | _216_;
  assign _221_ = _220_ | _213_;
  assign _222_ = ~(_221_ | _208_);
  assign _231_[16] = _222_ ^ \genSndRec.count_r [16];
  assign _223_ = _222_ & \genSndRec.count_r [16];
  assign _231_[17] = _223_ ^ \genSndRec.count_r [17];
  assign _224_ = ~(\genSndRec.count_r [17] & \genSndRec.count_r [16]);
  assign _225_ = _222_ & ~(_224_);
  assign _231_[18] = _225_ ^ \genSndRec.count_r [18];
  assign spi_sck_o = \SerialClock.clk_r  & \SPI_Int.CE ;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [0] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [0] <= \SPI_Ctrl.tmpSR [0];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [1] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [1] <= \SPI_Ctrl.tmpSR [1];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [2] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [2] <= \SPI_Ctrl.tmpSR [2];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [3] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [3] <= \SPI_Ctrl.tmpSR [3];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [4] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [4] <= \SPI_Ctrl.tmpSR [4];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [5] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [5] <= \SPI_Ctrl.tmpSR [5];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [6] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [6] <= \SPI_Ctrl.tmpSR [6];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [7] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [7] <= \SPI_Ctrl.tmpSR [7];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [8] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [8] <= \SPI_Ctrl.tmpSR [8];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [9] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [9] <= \SPI_Ctrl.tmpSR [9];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [10] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [10] <= \SPI_Ctrl.tmpSR [10];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [11] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [11] <= \SPI_Ctrl.tmpSR [11];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [12] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [12] <= \SPI_Ctrl.tmpSR [12];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [13] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [13] <= \SPI_Ctrl.tmpSR [13];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [14] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [14] <= \SPI_Ctrl.tmpSR [14];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [15] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [15] <= \SPI_Ctrl.tmpSR [15];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [16] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [16] <= \SPI_Ctrl.tmpSR [16];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [17] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [17] <= \SPI_Ctrl.tmpSR [17];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [18] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [18] <= \SPI_Ctrl.tmpSR [18];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [19] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [19] <= \SPI_Ctrl.tmpSR [19];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [20] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [20] <= \SPI_Ctrl.tmpSR [20];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [21] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [21] <= \SPI_Ctrl.tmpSR [21];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [22] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [22] <= \SPI_Ctrl.tmpSR [22];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [23] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [23] <= \SPI_Ctrl.tmpSR [23];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [24] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [24] <= \SPI_Ctrl.tmpSR [24];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [25] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [25] <= \SPI_Ctrl.tmpSR [25];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [26] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [26] <= \SPI_Ctrl.tmpSR [26];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [27] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [27] <= \SPI_Ctrl.tmpSR [27];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [28] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [28] <= \SPI_Ctrl.tmpSR [28];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [29] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [29] <= \SPI_Ctrl.tmpSR [29];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [30] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [30] <= \SPI_Ctrl.tmpSR [30];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [31] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [31] <= \SPI_Ctrl.tmpSR [31];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [32] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [32] <= \SPI_Ctrl.tmpSR [32];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [33] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [33] <= \SPI_Ctrl.tmpSR [33];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [34] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [34] <= \SPI_Ctrl.tmpSR [34];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [35] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [35] <= \SPI_Ctrl.tmpSR [35];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [36] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [36] <= \SPI_Ctrl.tmpSR [36];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [37] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [37] <= \SPI_Ctrl.tmpSR [37];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [38] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [38] <= \SPI_Ctrl.tmpSR [38];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.DOUT [39] <= 1'h0;
    else if (_146_) \SPI_Ctrl.DOUT [39] <= \SPI_Ctrl.tmpSR [39];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.sndData [0] <= 1'h0;
    else if (_001_) \SPI_Ctrl.sndData [0] <= _014_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.sndData [1] <= 1'h0;
    else if (_001_) \SPI_Ctrl.sndData [1] <= _015_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.sndData [2] <= 1'h0;
    else if (_001_) \SPI_Ctrl.sndData [2] <= _016_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.sndData [3] <= 1'h0;
    else if (_001_) \SPI_Ctrl.sndData [3] <= _017_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.sndData [4] <= 1'h0;
    else if (_001_) \SPI_Ctrl.sndData [4] <= _018_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.sndData [5] <= 1'h0;
    else if (_001_) \SPI_Ctrl.sndData [5] <= _019_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.sndData [6] <= 1'h0;
    else if (_001_) \SPI_Ctrl.sndData [6] <= _020_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.sndData [7] <= 1'h0;
    else if (_001_) \SPI_Ctrl.sndData [7] <= _021_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.getByte  <= 1'h0;
    else if (_002_) \SPI_Ctrl.getByte  <= _022_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.SS  <= 1'h1;
    else if (_003_) \SPI_Ctrl.SS  <= _010_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.byteCnt [0] <= 1'h0;
    else if (_006_) \SPI_Ctrl.byteCnt [0] <= _103_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.byteCnt [1] <= 1'h0;
    else if (_006_) \SPI_Ctrl.byteCnt [1] <= _104_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.byteCnt [2] <= 1'h0;
    else if (_006_) \SPI_Ctrl.byteCnt [2] <= _105_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [0] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [0] <= _063_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [1] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [1] <= _074_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [2] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [2] <= _085_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [3] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [3] <= _096_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [4] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [4] <= _097_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [5] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [5] <= _098_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [6] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [6] <= _099_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [7] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [7] <= _100_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [8] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [8] <= _101_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [9] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [9] <= _102_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [10] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [10] <= _064_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [11] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [11] <= _065_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [12] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [12] <= _066_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [13] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [13] <= _067_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [14] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [14] <= _068_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [15] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [15] <= _069_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [16] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [16] <= _070_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [17] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [17] <= _071_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [18] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [18] <= _072_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [19] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [19] <= _073_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [20] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [20] <= _075_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [21] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [21] <= _076_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [22] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [22] <= _077_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [23] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [23] <= _078_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [24] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [24] <= _079_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [25] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [25] <= _080_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [26] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [26] <= _081_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [27] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [27] <= _082_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [28] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [28] <= _083_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [29] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [29] <= _084_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [30] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [30] <= _086_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [31] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [31] <= _087_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [32] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [32] <= _088_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [33] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [33] <= _089_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [34] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [34] <= _090_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [35] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [35] <= _091_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [36] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [36] <= _092_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [37] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [37] <= _093_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [38] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [38] <= _094_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSR [39] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSR [39] <= _095_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [0] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [0] <= _023_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [1] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [1] <= _034_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [2] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [2] <= _045_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [3] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [3] <= _056_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [4] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [4] <= _057_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [5] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [5] <= _058_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [6] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [6] <= _059_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [7] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [7] <= _060_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [8] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [8] <= _061_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [9] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [9] <= _062_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [10] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [10] <= _024_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [11] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [11] <= _025_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [12] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [12] <= _026_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [13] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [13] <= _027_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [14] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [14] <= _028_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [15] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [15] <= _029_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [16] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [16] <= _030_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [17] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [17] <= _031_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [18] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [18] <= _032_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [19] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [19] <= _033_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [20] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [20] <= _035_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [21] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [21] <= _036_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [22] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [22] <= _037_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [23] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [23] <= _038_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [24] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [24] <= _039_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [25] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [25] <= _040_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [26] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [26] <= _041_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [27] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [27] <= _042_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [28] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [28] <= _043_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [29] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [29] <= _044_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [30] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [30] <= _046_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [31] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [31] <= _047_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [32] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [32] <= _048_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [33] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [33] <= _049_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [34] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [34] <= _050_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [35] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [35] <= _051_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [36] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [36] <= _052_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [37] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [37] <= _053_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [38] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [38] <= _054_;
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.tmpSRsend [39] <= 1'h0;
    else if (_000_) \SPI_Ctrl.tmpSRsend [39] <= _055_;
  (* \always_ff  = 32'd1 *)
  (* src = "PmodJSTK.sv:66.4-70.7|ClkDiv_20Hz.sv:14.4-29.7" *)
  always @(posedge clk_12mhz_i)
    if (_007_) \genSndRec.count_r [0] <= 1'h0;
    else \genSndRec.count_r [0] <= _230_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "PmodJSTK.sv:66.4-70.7|ClkDiv_20Hz.sv:14.4-29.7" *)
  always @(posedge clk_12mhz_i)
    if (_007_) \genSndRec.count_r [1] <= 1'h0;
    else \genSndRec.count_r [1] <= _231_[1];
  (* \always_ff  = 32'd1 *)
  (* src = "PmodJSTK.sv:66.4-70.7|ClkDiv_20Hz.sv:14.4-29.7" *)
  always @(posedge clk_12mhz_i)
    if (_007_) \genSndRec.count_r [2] <= 1'h0;
    else \genSndRec.count_r [2] <= _231_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "PmodJSTK.sv:66.4-70.7|ClkDiv_20Hz.sv:14.4-29.7" *)
  always @(posedge clk_12mhz_i)
    if (_007_) \genSndRec.count_r [3] <= 1'h0;
    else \genSndRec.count_r [3] <= _231_[3];
  (* \always_ff  = 32'd1 *)
  (* src = "PmodJSTK.sv:66.4-70.7|ClkDiv_20Hz.sv:14.4-29.7" *)
  always @(posedge clk_12mhz_i)
    if (_007_) \genSndRec.count_r [4] <= 1'h0;
    else \genSndRec.count_r [4] <= _231_[4];
  (* \always_ff  = 32'd1 *)
  (* src = "PmodJSTK.sv:66.4-70.7|ClkDiv_20Hz.sv:14.4-29.7" *)
  always @(posedge clk_12mhz_i)
    if (_007_) \genSndRec.count_r [5] <= 1'h0;
    else \genSndRec.count_r [5] <= _231_[5];
  (* \always_ff  = 32'd1 *)
  (* src = "PmodJSTK.sv:66.4-70.7|ClkDiv_20Hz.sv:14.4-29.7" *)
  always @(posedge clk_12mhz_i)
    if (_007_) \genSndRec.count_r [6] <= 1'h0;
    else \genSndRec.count_r [6] <= _231_[6];
  (* \always_ff  = 32'd1 *)
  (* src = "PmodJSTK.sv:66.4-70.7|ClkDiv_20Hz.sv:14.4-29.7" *)
  always @(posedge clk_12mhz_i)
    if (_007_) \genSndRec.count_r [7] <= 1'h0;
    else \genSndRec.count_r [7] <= _231_[7];
  (* \always_ff  = 32'd1 *)
  (* src = "PmodJSTK.sv:66.4-70.7|ClkDiv_20Hz.sv:14.4-29.7" *)
  always @(posedge clk_12mhz_i)
    if (_007_) \genSndRec.count_r [8] <= 1'h0;
    else \genSndRec.count_r [8] <= _231_[8];
  (* \always_ff  = 32'd1 *)
  (* src = "PmodJSTK.sv:66.4-70.7|ClkDiv_20Hz.sv:14.4-29.7" *)
  always @(posedge clk_12mhz_i)
    if (_007_) \genSndRec.count_r [9] <= 1'h0;
    else \genSndRec.count_r [9] <= _231_[9];
  (* \always_ff  = 32'd1 *)
  (* src = "PmodJSTK.sv:66.4-70.7|ClkDiv_20Hz.sv:14.4-29.7" *)
  always @(posedge clk_12mhz_i)
    if (_007_) \genSndRec.count_r [10] <= 1'h0;
    else \genSndRec.count_r [10] <= _231_[10];
  (* \always_ff  = 32'd1 *)
  (* src = "PmodJSTK.sv:66.4-70.7|ClkDiv_20Hz.sv:14.4-29.7" *)
  always @(posedge clk_12mhz_i)
    if (_007_) \genSndRec.count_r [11] <= 1'h0;
    else \genSndRec.count_r [11] <= _231_[11];
  (* \always_ff  = 32'd1 *)
  (* src = "PmodJSTK.sv:66.4-70.7|ClkDiv_20Hz.sv:14.4-29.7" *)
  always @(posedge clk_12mhz_i)
    if (_007_) \genSndRec.count_r [12] <= 1'h0;
    else \genSndRec.count_r [12] <= _231_[12];
  (* \always_ff  = 32'd1 *)
  (* src = "PmodJSTK.sv:66.4-70.7|ClkDiv_20Hz.sv:14.4-29.7" *)
  always @(posedge clk_12mhz_i)
    if (_007_) \genSndRec.count_r [13] <= 1'h0;
    else \genSndRec.count_r [13] <= _231_[13];
  (* \always_ff  = 32'd1 *)
  (* src = "PmodJSTK.sv:66.4-70.7|ClkDiv_20Hz.sv:14.4-29.7" *)
  always @(posedge clk_12mhz_i)
    if (_007_) \genSndRec.count_r [14] <= 1'h0;
    else \genSndRec.count_r [14] <= _231_[14];
  (* \always_ff  = 32'd1 *)
  (* src = "PmodJSTK.sv:66.4-70.7|ClkDiv_20Hz.sv:14.4-29.7" *)
  always @(posedge clk_12mhz_i)
    if (_007_) \genSndRec.count_r [15] <= 1'h0;
    else \genSndRec.count_r [15] <= _231_[15];
  (* \always_ff  = 32'd1 *)
  (* src = "PmodJSTK.sv:66.4-70.7|ClkDiv_20Hz.sv:14.4-29.7" *)
  always @(posedge clk_12mhz_i)
    if (_007_) \genSndRec.count_r [16] <= 1'h0;
    else \genSndRec.count_r [16] <= _231_[16];
  (* \always_ff  = 32'd1 *)
  (* src = "PmodJSTK.sv:66.4-70.7|ClkDiv_20Hz.sv:14.4-29.7" *)
  always @(posedge clk_12mhz_i)
    if (_007_) \genSndRec.count_r [17] <= 1'h0;
    else \genSndRec.count_r [17] <= _231_[17];
  (* \always_ff  = 32'd1 *)
  (* src = "PmodJSTK.sv:66.4-70.7|ClkDiv_20Hz.sv:14.4-29.7" *)
  always @(posedge clk_12mhz_i)
    if (_007_) \genSndRec.count_r [18] <= 1'h0;
    else \genSndRec.count_r [18] <= _231_[18];
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:137.4-221.7" *)
  always @(negedge \SerialClock.clk_r )
    if (_009_) \SPI_Int.bitCount [0] <= 1'h0;
    else \SPI_Int.bitCount [0] <= _226_[0];
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:137.4-221.7" *)
  always @(negedge \SerialClock.clk_r )
    if (_009_) \SPI_Int.bitCount [1] <= 1'h0;
    else \SPI_Int.bitCount [1] <= _227_[1];
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:137.4-221.7" *)
  always @(negedge \SerialClock.clk_r )
    if (_009_) \SPI_Int.bitCount [2] <= 1'h0;
    else \SPI_Int.bitCount [2] <= _227_[2];
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:137.4-221.7" *)
  always @(negedge \SerialClock.clk_r )
    if (_009_) \SPI_Int.bitCount [3] <= 1'h0;
    else \SPI_Int.bitCount [3] <= _227_[3];
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:137.4-221.7" *)
  always @(negedge \SerialClock.clk_r )
    if (_009_) \SPI_Int.bitCount [4] <= 1'h0;
    else \SPI_Int.bitCount [4] <= _227_[4];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.pState [0] <= 1'h0;
    else \SPI_Ctrl.pState [0] <= _232_[0];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.pState [1] <= 1'h0;
    else \SPI_Ctrl.pState [1] <= _232_[1];
  (* src = "PmodJSTK.sv:27.4-38.7|spiCtrl.v:60.4-183.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Ctrl.pState [2] <= 1'h0;
    else \SPI_Ctrl.pState [2] <= _232_[2];
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:137.4-221.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Int.BUSY  <= 1'h0;
    else \SPI_Int.BUSY  <= _011_;
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:137.4-221.7" *)
  always @(negedge \SerialClock.clk_r )
    if (_009_) \SPI_Int.CE  <= 1'h0;
    else \SPI_Int.CE  <= _106_;
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:137.4-221.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Int.pState [0] <= 1'h0;
    else \SPI_Int.pState [0] <= _233_[0];
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:137.4-221.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Int.pState [1] <= 1'h0;
    else \SPI_Int.pState [1] <= _233_[1];
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:103.4-129.7" *)
  always @(posedge \SerialClock.clk_r )
    if (reset_i) \SPI_Int.rSR [0] <= 1'h0;
    else if (_005_) \SPI_Int.rSR [0] <= spi_sd_i;
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:103.4-129.7" *)
  always @(posedge \SerialClock.clk_r )
    if (reset_i) \SPI_Int.rSR [1] <= 1'h0;
    else if (_005_) \SPI_Int.rSR [1] <= \SPI_Int.rSR [0];
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:103.4-129.7" *)
  always @(posedge \SerialClock.clk_r )
    if (reset_i) \SPI_Int.rSR [2] <= 1'h0;
    else if (_005_) \SPI_Int.rSR [2] <= \SPI_Int.rSR [1];
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:103.4-129.7" *)
  always @(posedge \SerialClock.clk_r )
    if (reset_i) \SPI_Int.rSR [3] <= 1'h0;
    else if (_005_) \SPI_Int.rSR [3] <= \SPI_Int.rSR [2];
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:103.4-129.7" *)
  always @(posedge \SerialClock.clk_r )
    if (reset_i) \SPI_Int.rSR [4] <= 1'h0;
    else if (_005_) \SPI_Int.rSR [4] <= \SPI_Int.rSR [3];
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:103.4-129.7" *)
  always @(posedge \SerialClock.clk_r )
    if (reset_i) \SPI_Int.rSR [5] <= 1'h0;
    else if (_005_) \SPI_Int.rSR [5] <= \SPI_Int.rSR [4];
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:103.4-129.7" *)
  always @(posedge \SerialClock.clk_r )
    if (reset_i) \SPI_Int.rSR [6] <= 1'h0;
    else if (_005_) \SPI_Int.rSR [6] <= \SPI_Int.rSR [5];
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:103.4-129.7" *)
  always @(posedge \SerialClock.clk_r )
    if (reset_i) \SPI_Int.rSR [7] <= 1'h0;
    else if (_005_) \SPI_Int.rSR [7] <= \SPI_Int.rSR [6];
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:67.4-93.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Int.wSR [0] <= 1'h0;
    else if (_004_) \SPI_Int.wSR [0] <= _107_;
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:67.4-93.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Int.wSR [1] <= 1'h0;
    else if (_004_) \SPI_Int.wSR [1] <= _108_;
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:67.4-93.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Int.wSR [2] <= 1'h0;
    else if (_004_) \SPI_Int.wSR [2] <= _109_;
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:67.4-93.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Int.wSR [3] <= 1'h0;
    else if (_004_) \SPI_Int.wSR [3] <= _110_;
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:67.4-93.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Int.wSR [4] <= 1'h0;
    else if (_004_) \SPI_Int.wSR [4] <= _111_;
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:67.4-93.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Int.wSR [5] <= 1'h0;
    else if (_004_) \SPI_Int.wSR [5] <= _112_;
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:67.4-93.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Int.wSR [6] <= 1'h0;
    else if (_004_) \SPI_Int.wSR [6] <= _113_;
  (* src = "PmodJSTK.sv:42.4-52.8|spiMode0.sv:67.4-93.7" *)
  always @(negedge \SerialClock.clk_r )
    if (reset_i) \SPI_Int.wSR [7] <= 1'h0;
    else if (_004_) \SPI_Int.wSR [7] <= _114_;
  (* \always_ff  = 32'd1 *)
  (* src = "PmodJSTK.sv:57.4-61.7|ClkDiv_66_67kHz.sv:17.4-32.7" *)
  always @(posedge clk_12mhz_i)
    if (reset_i) \SerialClock.clk_r  <= 1'h0;
    else if (!_012_) \SerialClock.clk_r  <= _115_;
  (* \always_ff  = 32'd1 *)
  (* src = "PmodJSTK.sv:66.4-70.7|ClkDiv_20Hz.sv:14.4-29.7" *)
  always @(posedge clk_12mhz_i)
    if (reset_i) \genSndRec.clk_r  <= 1'h0;
    else if (!_013_) \genSndRec.clk_r  <= _116_;
  (* \always_ff  = 32'd1 *)
  (* src = "PmodJSTK.sv:57.4-61.7|ClkDiv_66_67kHz.sv:17.4-32.7" *)
  always @(posedge clk_12mhz_i)
    if (_008_) \SerialClock.count_r [0] <= 1'h0;
    else \SerialClock.count_r [0] <= _228_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "PmodJSTK.sv:57.4-61.7|ClkDiv_66_67kHz.sv:17.4-32.7" *)
  always @(posedge clk_12mhz_i)
    if (_008_) \SerialClock.count_r [1] <= 1'h0;
    else \SerialClock.count_r [1] <= _229_[1];
  (* \always_ff  = 32'd1 *)
  (* src = "PmodJSTK.sv:57.4-61.7|ClkDiv_66_67kHz.sv:17.4-32.7" *)
  always @(posedge clk_12mhz_i)
    if (_008_) \SerialClock.count_r [2] <= 1'h0;
    else \SerialClock.count_r [2] <= _229_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "PmodJSTK.sv:57.4-61.7|ClkDiv_66_67kHz.sv:17.4-32.7" *)
  always @(posedge clk_12mhz_i)
    if (_008_) \SerialClock.count_r [3] <= 1'h0;
    else \SerialClock.count_r [3] <= _229_[3];
  (* \always_ff  = 32'd1 *)
  (* src = "PmodJSTK.sv:57.4-61.7|ClkDiv_66_67kHz.sv:17.4-32.7" *)
  always @(posedge clk_12mhz_i)
    if (_008_) \SerialClock.count_r [4] <= 1'h0;
    else \SerialClock.count_r [4] <= _229_[4];
  (* \always_ff  = 32'd1 *)
  (* src = "PmodJSTK.sv:57.4-61.7|ClkDiv_66_67kHz.sv:17.4-32.7" *)
  always @(posedge clk_12mhz_i)
    if (_008_) \SerialClock.count_r [5] <= 1'h0;
    else \SerialClock.count_r [5] <= _229_[5];
  (* \always_ff  = 32'd1 *)
  (* src = "PmodJSTK.sv:57.4-61.7|ClkDiv_66_67kHz.sv:17.4-32.7" *)
  always @(posedge clk_12mhz_i)
    if (_008_) \SerialClock.count_r [6] <= 1'h0;
    else \SerialClock.count_r [6] <= _229_[6];
  assign _227_[0] = _226_[0];
  assign _228_[6:1] = \SerialClock.count_r [6:1];
  assign _229_[0] = _228_[0];
  assign _230_[18:1] = \genSndRec.count_r [18:1];
  assign _231_[0] = _230_[0];
  assign \SPI_Ctrl.BUSY  = \SPI_Int.BUSY ;
  assign \SPI_Ctrl.DIN  = data_i;
  assign \SPI_Ctrl.RxData  = \SPI_Int.rSR ;
  assign \SPI_Ctrl.clk_i  = \SerialClock.clk_r ;
  assign \SPI_Ctrl.reset_i  = reset_i;
  assign \SPI_Ctrl.sndRec  = \genSndRec.clk_r ;
  assign \SPI_Int.CLK  = \SerialClock.clk_r ;
  assign \SPI_Int.DIN  = \SPI_Ctrl.sndData ;
  assign \SPI_Int.DOUT  = \SPI_Int.rSR ;
  assign \SPI_Int.MISO  = spi_sd_i;
  assign \SPI_Int.MOSI  = \SPI_Int.wSR [7];
  assign \SPI_Int.RST  = reset_i;
  assign \SPI_Int.SCLK  = spi_sck_o;
  assign \SPI_Int.sndRec  = \SPI_Ctrl.getByte ;
  assign \SerialClock.clk_i  = clk_12mhz_i;
  assign \SerialClock.clk_o  = \SerialClock.clk_r ;
  assign \SerialClock.reset_i  = reset_i;
  assign busy_o = \SPI_Int.BUSY ;
  assign clk_20hz_o = \genSndRec.clk_r ;
  assign clk_66_67khz_o = \SerialClock.clk_r ;
  assign data_o = \SPI_Ctrl.DOUT ;
  assign \genSndRec.clk_i  = clk_12mhz_i;
  assign \genSndRec.clk_o  = \genSndRec.clk_r ;
  assign \genSndRec.reset_i  = reset_i;
  assign rx_data_i = \SPI_Int.rSR ;
  assign spi_cs_o = \SPI_Ctrl.SS ;
  assign spi_sd_o = \SPI_Int.wSR [7];
  assign tx_data_o = \SPI_Ctrl.sndData ;
  assign tx_not_rx = \SPI_Ctrl.getByte ;
endmodule
/* verilator lint_on DECLFILENAME */
